config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  scope module: :frontend do
    root to: 'main#home'
    resources :products, only: %i[index show]
    resources :buys, only: [:index, :show] do
      get 'create', to: 'buys#create', on: :collection, as: :create
    end
    get 'cart', to: 'cart#show'
    get 'add_product_to_cart/:id', to: 'cart#add_to_cart', as: 'add_product_to_cart'
    get 'remove_from_cart/:id', to: 'cart#remove_from_cart', as: 'remove_product_from_cart'
  end

  namespace :backend do
    root 'main#index'
    resources :users
    resources :categories
    resources :tags
    resources :sliders
    resources :products
    resources :clients, only: %i[index destroy]
    resources :configs, except: %i[show destroy index edit] do
      get 'edit', on: :collection
    end

    resources :buys, only: %i[index show] do
      member do
        put :state_change_accepted
        put :state_change_rejected
      end
    end
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  # -- Relations
  belongs_to :category
  has_many :product_tags
  has_many :tags, through: :product_tags
  has_many :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images, allow_destroy: true
  has_many :items

  # -- Validations
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :code, presence: true, uniqueness: true
  validates :category, presence: true
  validates :price,
            presence: true,
            numericality: {
              greater_than_or_equal_to: 0
            }
  validates :cost,
            presence: true,
            numericality: {
              greater_than_or_equal_to: 0
            }
  validate :only_one_image_checked

  before_destroy :check_buys



  # -- Scopes
  scope :with_name, ->(name) { where('name LIKE ?', "%#{name}%") }
  scope :with_category, ->(category_id) { where(category_id: category_id) }
  # scope :sort_asc_name,->{ order(name: :asc) }
  # scope :sort_desc_name, ->{ order(name: :desc) }
  scope :sort_name, ->(sort) { order(name: sort) }
  scope :actives, -> { where(active: true) }
  def only_one_image_checked
    return if product_images.select(&:principal).count == 1

    errors.add(:product_images, message: I18n.t(:only_one_image_error))
  end
  private 

  def check_buys
    return if self.items.count.zero?

    errors.add(:base, I18n.t(:destroy_products_error))
    throw(:abort)
  end
end

app/controllers/backend/products_controller.rb
# frozen_string_literal: true

module Backend
  class ProductsController < BackendController
    before_action :set_product, only: %i[
      show
      edit
      update
      destroy
    ]
    before_action :authorize_product
    def index
      @presenter = ProductBackendPresenter.new(params)
    end

    def show; end

    def new
      @product = Product.new
    end

    def edit; end

    def create
      #binding.pry
      @product = Product.new(product_params)
      if @product.save
        flash[:notice] = t(:action_without_errors,
                               element: :Producto,
                               action: :creado)
        redirect_to backend_products_path
      else
       # binding.pry
        flash[:alert] = t(:action_error,
                              element: :Producto,
                              action: :creado)
        render :new
      end
    end

    def update
      if @product.update(product_params)
        flash[:notice] = t(:action_without_errors,
                               element: :Producto,
                               action: :actualizado)
        redirect_to backend_products_path
      else
        flash[:alert] = t(:action_error,
                              element: :Producto,
                              action: :actualizado)
        render :edit
      end
    end

    def destroy
      @product.destroy
      if @product.errors.present?
        flash[:alert] = @product.errors.full_messages.first
      else
        flash[:notice] = t(:action_without_errors,
          element: :Producto,
          action: :eliminado)
      end
      redirect_to backend_products_path
    end

    private

    def authorize_product
      authorize! :authorize_product, :backend_product
    end

    def set_product
      @product = Product.find(params[:id]).decorate
    end

    def product_params
      params.require(:product).permit(
        :name,
        :description,
        :active,
        :code,
        :price,
        :cost,
        :category_id,
        tag_ids: [],
        product_images_attributes: %i[
          id
          image
          principal
          _destroy
        ]
      )
    end
  end
end

app/controllers/frontend/buys_controller.rb
# frozen_string_literal: true
module Frontend
  class BuysController < FrontendController
    before_action :authorize_buy_client_logged

    def index
      @buys = current_user.buys
    end

    def show
      @buy = Buy.find(params[:id]).decorate
    end

    def create
      buy_manager = BuyManager.new(@cart, current_user)

      if buy_manager.create
        flash.now[:notice] = t(:buy_created_without_errors)
        redirect_to buys_path
      else
        flash.now[:alert] = t(:buy_created_without_errors)
        redirect_to cart_path
      end
    end

    private

    def authorize_buy_client_logged
      authorize! :authorize_buy_user_logged, :frontend_buy
    end
  end
end

app/controllers/frontend/cart_controller.rb
# frozen_string_literal: true
module Frontend
  class CartController < FrontendController
    #before_action :authorize_cart
    before_action :set_product_id, only: [:add_to_cart, :remove_from_cart]
    def show
      if @cart.size.zero?
        flash[:alert] = t(:the_cart_does_not_have_products)
        redirect_to root_path
      end
      @elements_cart = Cart.new(@cart)
    end

    def add_to_cart
      product_id = params[:id]
      if @cart[product_id].nil?
        @cart[product_id] = 1
      else
        @cart[product_id] += 1
      end
      render 'update_cart_notification'
    end

    def authorize_cart
      authorize! :authorize_cart, :frontend_cart
    end

    def remove_from_cart
      @cart.delete(params[:id])
      @elements_cart = Cart.new(@cart)
    end

    private

    def set_product_id
      @product_id = params[:id]
    end
  end
end

app/controllers/frontend/item_controller.rb
module Frontend
  class ItemController < FrontendController
    before_action :set_item

    def show; end

    def create; end

    private

    def set_item
      @item = Item.find(params[:id])
    end
  end
end

app/controllers/frontend/main_controller.rb
# frozen_string_literal: true

module Frontend
  class MainController < FrontendController
    #before_action :authorize_home
    def home
      @sliders = Slider.all
      @products = Product.actives.order("RAND()").limit(4).decorate
    end
  end
end

app/controllers/frontend/products_controller.rb
# frozen_string_literal: true

module Frontend
  class ProductsController < FrontendController
    #before_action :authorize_product
    def index
      @presenter = ProductPresenter.new(params)
      #@presenter = Product.all
    end

    def show
      @product = Product.find(params[:id]).decorate
    end
  end
end

app/controllers/frontend_controller.rb
# frozen_string_literal: true

class FrontendController < ApplicationController
end

app/views/frontend/products/_filter.html.erb
<br>
<div class='d-flex justify-content-between form-group bg-secondary p-3 mb-2 text-white text-left'>
  <h2> <%= I18n.t(:products) %> </h2>
  <%= form_with url: products_path, model:@presenter.filter,
                local:true,
                remote:true,
                method: :get, class: 'form-inline' do |f|
  %>
  <div class="form-group mx-sm-3 mb-2">
    <%= f.select(:sort, [['Ordenado A-Z', :asc], ['Ordenado Z-A', :desc]],{ include_blank: I18n.t(:order) }, class: 'form-control mb-2 ') %>
  </div><br>
  <div class="form-group mx-sm-3 mb-2">
    <%= f.collection_select :category_id, Category.all, :id, :name, { include_blank: I18n.t(:all) }, class: 'form-control mb-2 mr-sm-2' %>
  </div>
  <div class="form-group mx-sm-3 mb-2">
    <%= f.text_field :query, class: 'form-control mb-2 mr-sm-2' %>
    <%= f.submit I18n.t(:find), class: 'btn btn-info mb-2' %>
  </div>
  <% end %>
</div>

app/views/frontend/products/_product.html.erb
<div class="col">
<div class="card">
  <div class="card border" style="width: 90%;">
    <%= image_tag(product.image_principal, class: 'card-img-top', size: "300x180") %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= product.name %></p>
        <%= link_to image_tag("cart2.png", size: "25x25"), add_product_to_cart_path(product.id), remote: true, class: "btn btn-success text-left"%>
      <div class="col-sm text-right">
        <%= product.pretty_price %>
      </div >
    <br>
    <%= link_to I18n.t(:show), product_path(product),  class: 'btn btn-primary btn-lg btn-block' %>
  </div>
</div>
</div>

app/views/frontend/products/index.html.erb
<%= render 'filter' %>
<div class="row">
  <table class="table">
    <tbody>
      <%= render @presenter.products %>
    </tbody>
  </table>
</div>
<br>
<div class="row d-flex justify-content-center">
  <%= will_paginate @presenter.products%>
</div>

app/views/frontend/products/show.html.erb
<div class="p-3 mb-2 bg-secondary text-white">
  <h2>
    <%= @product.name%>
  </h2>
</div>
<div class="container-fluid">
<div class="row">
<div class="col-8">
  <div class="row">
    <div class="col">
      <p class="text-secondary"><%= I18n.t(:category) %></p>
      <%= @product.category_name%>
    </div>
    <div class="col">
    <p class="text-secondary"><%= I18n.t(:price) %></p>
    <%= @product.pretty_price%>
    </div>
  </div>
<div class="row">
  <div class="col">
    <p class="text-secondary"><%= I18n.t(:tags) %></p>
    <%=@product.tags_name%>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <p class="text-secondary"> <%= I18n.t(:description) %></p>
    <%= @product.description%>
  </div>
</div>
</div>
<div class="col-4">
  <div class="text-center">
    <%= image_tag(@product.image_principal, size: "300x300")%>
  </div>
  <br>
  <div class="container-fluid">
    <div class="row flex-nowrap" style="overflow:auto">
      <% @product.images_secondaries.each do |prod| %>
        <div class="col-2">
          <div class="card card-block">
            <%= image_tag(prod, size: "100x100") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>
</div>
<div class='card-footer'>
  <%= link_to I18n.t(:all_products), products_path, class: 'btn btn-outline-secondary' %>
</div>