config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  scope module: :frontend do
    root to: 'main#home'
    resources :products, only: %i[index show]
    resources :buys, only: [:index, :show] do
      get 'create', to: 'buys#create', on: :collection, as: :create
    end
    get 'cart', to: 'cart#show'
    get 'add_product_to_cart/:id', to: 'cart#add_to_cart', as: 'add_product_to_cart'
    get 'remove_from_cart/:id', to: 'cart#remove_from_cart', as: 'remove_product_from_cart'
  end

  namespace :backend do
    root 'main#index'
    resources :users
    resources :categories
    resources :tags
    resources :sliders
    resources :products
    resources :clients, only: %i[index destroy]
    resources :configs, except: %i[show destroy index edit] do
      get 'edit', on: :collection
    end

    resources :buys, only: %i[index show] do
      member do
        put :state_change_accepted
        put :state_change_rejected
      end
    end
  end
end

app/models/buy.rb
# frozen_string_literal: true

class Buy < ApplicationRecord
  # -- Relations
  belongs_to :user
  has_many :items

  enum state: [:pending, :accepted, :rejected]

  # -- Validations
  validate :profile_client
  validates :items, presence: true

  #---atributos extras
  def profile_client
    user = User.find(user_id)
    return if user.profile.client?

    errors.add(:user_id, I18n.t('profile.error.wrong_profile'))
  end

  def total_buy
    items.sum(&:subtotal)
  end

  def item_count
    items.sum(&:count)
  end

  def update_state(state_new)
    if pending?
      update(state: state_new)
      true
    else
      errors.add(:state, I18n.t(:inmmutable_state_error))
      false
    end
  end
end

app/controllers/backend/buys_controller.rb
# frozen_string_literal: true

module Backend
  class BuysController < BackendController
    # authorize_resource class: false
    before_action :set_buy, except: [
      :index
    ]

    def index
      authorize! :index, :backend_buy
      @buys = Buy.all.decorate
    end

    def state_change_accepted
      if @buy.update_state(:accepted)
        flash.now[:notice] = t(:action_without_errors,
                               element: :Compra,
                               action: :actualizada)
      else
        flash.now[:alert] = t(:action_error,
                              element: :Compra,
                              action: :actualizada)
      end
      @buy.decorate
    end

    def state_change_rejected
      if @buy.update_state(:rejected)
        flash.now[:notice] = t(:action_without_errors,
                               element: :Compra,
                               action: :actualizada)
      else
        flash.now[:alert] = t(:action_error,
                              element: :Compra,
                              action: :actualizada)
      end
      @buy.decorate
    end

    def show
      @buy
      authorize! :show, :backend_buy
    end

    private

    def set_buy
      @buy = Buy.find(params[:id]).decorate
    end

    def buy_params
      params.require(:buy).permit(:id)
    end
  end
end

app/controllers/backend/categories_controller.rb
# frozen_string_literal: true

module Backend
  class CategoriesController < BackendController
    authorize_resource
    before_action :set_category, only: %i[
      show
      edit
      update
      destroy
    ]
    def index
      @categories = Category.all
    end

    def show; end

    def new
      @category = Category.new
      render :modal
    end

    def edit
      render :modal
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        flash.now[:notice] = t(:action_without_errors,
                               element: :Categoría,
                               action: :creada)
      else
        flash.now[:alert] =  t(:action_error,
                               element: :Categoría,
                               action: :creada)
        render :modal
      end
    end

    def update
      if @category.update(category_params)
        flash.now[:notice] = t(:action_without_errors,
                               element: :Categoría,
                               action: :creada)
      else
        flash.now[:alert] = t(:action_error,
                              element: :Categoría,
                              action: :creada)
        render :modal
      end
    end

    def destroy
      @category.destroy
      if @category.errors.present?
        flash[:alert] = @category.errors.full_messages.first
      else
        flash[:notice] = t(:action_without_errors,
                           element: :Categoría,
                           action: :eliminada)
      end
      redirect_to backend_categories_path
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/controllers/backend/clients_controller.rb
# frozen_string_literal: true

module Backend
  class ClientsController < BackendController
    # authorize_resource class: false
    before_action :set_client, except: [
      :index
    ]
    before_action :authorize_buy
    def index
      @clients = User.clients
    end

    def show; end

    def destroy
      @client.destroy
      if @client.errors.present?
        flash.now[:alert] = @client.errors[:error_user_destroy].first
      else
        flash.now[:notice] = t(:action_without_errors,
                              element: :cliente,
                              action: :eliminado)
      end
    end

    private

    def authorize_buy
      authorize! :authorize_client, :backend_client
    end

    def set_client
      @client = User.find(params[:id])
    end

    def client_params
      params.require(:user).permit(:id)
    end
  end
end

app/controllers/backend/configs_controller.rb
# frozen_string_literal: true

module Backend
  class ConfigsController < BackendController
    authorize_resource
    def edit
      render :modal
    end

    def new
      render :modal
    end

    def create
      update
    end

    def update
      if @config.update(config_params)
        flash.now[:notice] = t(:action_without_errors,
                               element: :Conifugración,
                               action: :actualizada)
        redirect_to backend_sliders_path
      else
        flash.now[:alert] = t(:action_error,
                            element: :Configuración,
                            action: :actualizada)
        render :modal
      end
    end

    private

    def config_params
      params.require(:config).permit(
        :logo,
        :per_page
      )
    end
  end
end

app/controllers/backend/main_controller.rb
# frozen_string_literal: true

module Backend
  class MainController < BackendController
    before_action :authorize_main
    def index; end

    private

    def authorize_main
      authorize! :authorize_main, :backend_main
    end
  end
end

app/controllers/backend/products_controller.rb
# frozen_string_literal: true

module Backend
  class ProductsController < BackendController
    before_action :set_product, only: %i[
      show
      edit
      update
      destroy
    ]
    before_action :authorize_product
    def index
      @presenter = ProductBackendPresenter.new(params)
    end

    def show; end

    def new
      @product = Product.new
    end

    def edit; end

    def create
      #binding.pry
      @product = Product.new(product_params)
      if @product.save
        flash[:notice] = t(:action_without_errors,
                               element: :Producto,
                               action: :creado)
        redirect_to backend_products_path
      else
       # binding.pry
        flash[:alert] = t(:action_error,
                              element: :Producto,
                              action: :creado)
        render :new
      end
    end

    def update
      if @product.update(product_params)
        flash[:notice] = t(:action_without_errors,
                               element: :Producto,
                               action: :actualizado)
        redirect_to backend_products_path
      else
        flash[:alert] = t(:action_error,
                              element: :Producto,
                              action: :actualizado)
        render :edit
      end
    end

    def destroy
      @product.destroy
      if @product.errors.present?
        flash[:alert] = @product.errors.full_messages.first
      else
        flash[:notice] = t(:action_without_errors,
          element: :Producto,
          action: :eliminado)
      end
      redirect_to backend_products_path
    end

    private

    def authorize_product
      authorize! :authorize_product, :backend_product
    end

    def set_product
      @product = Product.find(params[:id]).decorate
    end

    def product_params
      params.require(:product).permit(
        :name,
        :description,
        :active,
        :code,
        :price,
        :cost,
        :category_id,
        tag_ids: [],
        product_images_attributes: %i[
          id
          image
          principal
          _destroy
        ]
      )
    end
  end
end

app/controllers/backend/sliders_controller.rb
# frozen_string_literal: true

module Backend
  class SlidersController < BackendController
    before_action :set_slider, only: %i[
      edit
      update
      destroy
    ]
    authorize_resource
    def index
      @sliders = Slider.all
      @config = Config.last
    end

    def new
      @slider = Slider.new
      render :modal
    end

    def edit
      render :modal
    end

    def create
      @slider = Slider.new(slider_params)
      if @slider.save
        flash.now[:notice] = t(:action_without_errors,
                               element: :Slider,
                               action: :creado)
      else
        flash.now[:alert] = t(:action_error,
                              element: :Slider,
                              action: :creado)
        
        render :modal
      end
    end

    def update
      if @slider.update(slider_params)
        flash.now[:notice] = t(:action_without_errors,
                               element: :Slider,
                               action: :creado)
      else
        flash.now[:alert] = t(:action_error,
                              element: :Slider,
                              action: :creado)
        render :modal
      end
    end

    def destroy
      @slider.destroy
      flash.now[:notice] = t(:action_without_errors,
                             element: :Slider,
                             action: :eliminado)
    end

    private

    def set_slider
      @slider = Slider.find(params[:id])
    end

    def slider_params
      params.require(:slider).permit(:name, :image)
    end
  end
end

app/controllers/backend/tags_controller.rb
# frozen_string_literal: true

module Backend
  class TagsController < BackendController
    before_action :set_tag, only: %i[
      edit
      update
      destroy
    ]
    authorize_resource
    def index
      @tags = Tag.all
    end

    def new
      @tag = Tag.new
      render :modal
    end

    def edit
      render :modal
    end

    def create
      @tag = Tag.new(tag_params)
      if @tag.save
        flash.now[:notice] = t(:action_without_errors,
                               element: :Tag,
                               action: :creado)
      else
        flash.now[:alert] = t(:action_error,
                              element: :Tag,
                              action: :creado)
        render :modal
      end
    end

    def update
      if @tag.update(tag_params)
        flash.now[:notice] = t(:action_without_errors,
                               element: :Tag,
                               action: :actualizado)
      else
        flash.now[:alert] = t(:action_error,
                              element: :Tag,
                              action: :actualizado)
        render :modal
      end
    end

    def destroy
      @tag.destroy
      flash.now[:notice] = t(:action_without_errors,
                             element: :Tag,
                             action: :eliminado)
    end

    private

    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name)
    end
  end
end

app/controllers/backend/users_controller.rb
# frozen_string_literal: true

module Backend
  class UsersController < BackendController
    before_action :set_user, only: %i[edit
                                      update
                                      destroy]
    authorize_resource
    def index
      @users = User.admins
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      @user.set_default_password
      @user.set_profile_admin
      if @user.save
        flash.now[:notice] = t(:action_without_errors,
                           element: :Usuario,
                           action: :creado)
        redirect_to backend_users_path
      else
        flash.now[:alert] = t(:action_error,
                              element: :Usuario,
                              action: :creado)
        render :new
      end
    end

    def edit; end

    def update
      if @user.update(user_params)
        flash.now[:notice] = t(:action_without_errors,
                           element: :Usuario,
                           action: :actualizado)
        redirect_to backend_users_path
      else
        flash.now[:alert] = t(:action_error,
                              element: :Usuario,
                              action: :actualizado)
        render :edit
      end
    end

    def destroy
      if @user != current_user
        @user.destroy
        flash.now[:notice] = t(:action_without_errors,
                           element: :Usuario,
                           action: :eliminado)
      else
        flash.now[:alert] = t(:action_error,
                          element: :Usuario,
                          action: :eliminado)
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :email)
    end
  end
end

app/controllers/backend_controller.rb
# frozen_string_literal: true

class BackendController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/frontend/buys_controller.rb
# frozen_string_literal: true
module Frontend
  class BuysController < FrontendController
    before_action :authorize_buy_client_logged

    def index
      @buys = current_user.buys
    end

    def show
      @buy = Buy.find(params[:id]).decorate
    end

    def create
      buy_manager = BuyManager.new(@cart, current_user)

      if buy_manager.create
        flash.now[:notice] = t(:buy_created_without_errors)
        redirect_to buys_path
      else
        flash.now[:alert] = t(:buy_created_without_errors)
        redirect_to cart_path
      end
    end

    private

    def authorize_buy_client_logged
      authorize! :authorize_buy_user_logged, :frontend_buy
    end
  end
end

app/views/backend/buys/_buy.html.erb
<tr id='<%= dom_id(buy) %>' >
  <td><%= buy.id %></td>
  <td><%= buy.client %></td>
  <td>
    <div class="row">
      <div class="col">
        <span class='js-state-container-<%= dom_id(buy) %>'>
          <%= buy.state_pretty %>
        </span>
      </div>
      <%= render partial: "state_change", locals: { buy: buy , context:'index_buy'} %>
    </div>
  </td>
  <td><%= buy.pretty_price_total %> </td>
  <td><%= buy.date%></td>
  <td>
    <%= link_to 'Ver', backend_buy_path(buy), method: :get, class: 'btn btn-sm btn-outline-info text-right' %>
  </td>
</tr>

app/views/backend/buys/_header_show.html.erb
<tr id='<%= dom_id(buy) %>'>
  <td><%= buy.client %></td>
  <td><%= buy.date %></td>
  <td>
  <div class="row">
    <div class='col js-state-container-<%= dom_id(@buy) %>'>
    <%= buy.state_pretty %>
    </div>
    <%= render partial: "state_change", locals: { buy: buy, context:'show_buy'} %>
  </div>
  </td>
</tr>

app/views/backend/buys/_state_change.erb
<% if buy.pending?%>
<div class="col">
  <%= link_to I18n.t(:accept), state_change_accepted_backend_buy_path(buy, source: context), method: :put, remote: true, data: { confirm: 'Esta seguro de aceptar?' }, class: 'btn btn-sm btn-outline-info text-right button-state' %>
</div>
<div class= "col">
  <%= link_to I18n.t(:reject), state_change_rejected_backend_buy_path(buy, source: context), method: :put, remote: true, data: { confirm: 'Esta seguro de rechazar?' }, class: 'btn btn-sm btn-outline-danger text-right button-state' %>
</div>
<% end %>

app/views/backend/buys/index.html.erb
<h3><%= I18n.t(:buys)%></h3>
<%= render 'flash_message' %>
<table class="table table-bordered">
  <thead class="thead-light">
    <tr>
      <th>#</th>
      <th><%= I18n.t(:client)%></th>
      <th><%= I18n.t(:state)%></th>
      <th><%= I18n.t(:total)%></th>
      <th><%= I18n.t(:date)%></th>
      <th><%= I18n.t(:options)%></th>
    </tr>
  </thead>
  <tbody id='buys_container'>
    <%= render @buys %>
  </tbody>
</table>

app/views/backend/buys/show.html.erb
<br>
<%= render 'flash_message' %>
<table class="table table-borderless">
  <thead>
    <tr class="text-secondary">
      
      <th scope="col"><%= I18n.t(:client) %></th>
      <th scope="col"><%= I18n.t(:date)%></th>
      <th scope="col"><%= I18n.t(:state)%></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "header_show", locals: { buy: @buy} %>
  </tbody>
</table>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col"></th>
      <th scope="col"><%= I18n.t(:product) %></th>
      <th scope="col"><%= I18n.t(:price) %></th>
      <th scope="col"><%= I18n.t(:count) %></th>
      <th scope="col"><%= I18n.t(:subtotal) %></th>
    </tr>
  </thead>
  <tbody>
   <%= render @buy.items %>
  <tr class="bg-secondary text-white">
   <td colspan="3"><%= I18n.t(:total) %></td>
   <td class= "text-left"> <%= @buy.item_count%> </td>
   <td colspan="2"> <h4><%= @buy.pretty_price_total%></h4> </td>
   </tr>
  </tbody>
</table>
 
  <div class='card-footer'>
    <%= link_to 'Volver', backend_buys_path, class: 'btn btn-outline-secondary' %>
  </div>

app/views/backend/buys/state_change_accepted.js.erb
$('#flash_messages_container').replaceWith('<%= j render 'flash_message' %>');
<% if params[:source] == 'show_buy'%>
 $('#<%= dom_id(@buy) %>').replaceWith('<%= j render 'header_show', buy: @buy %>');
<% elsif params[:source] == 'index_buy' %>
  $('#<%= dom_id(@buy) %>').replaceWith('<%= j render 'buy', buy: @buy %>');
<% end %>

app/views/backend/buys/state_change_rejected.js.erb
$('#flash_messages_container').replaceWith('<%= j render 'flash_message' %>')
<% if params[:source] == 'show_buy'%>
 $('#<%= dom_id(@buy) %>').replaceWith('<%= j render 'header_show', buy: @buy %>');
<% elsif params[:source] == 'index_buy' %>
  $('#<%= dom_id(@buy) %>').replaceWith('<%= j render 'buy', buy: @buy %>');
<% end %>