config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  scope module: :frontend do
    root to: 'main#home'
    resources :products, only: %i[index show]
    resources :buys, only: [:index, :show] do
      get 'create', to: 'buys#create', on: :collection, as: :create
    end
    get 'cart', to: 'cart#show'
    get 'add_product_to_cart/:id', to: 'cart#add_to_cart', as: 'add_product_to_cart'
    get 'remove_from_cart/:id', to: 'cart#remove_from_cart', as: 'remove_product_from_cart'
  end

  namespace :backend do
    root 'main#index'
    resources :users
    resources :categories
    resources :tags
    resources :sliders
    resources :products
    resources :clients, only: %i[index destroy]
    resources :configs, except: %i[show destroy index edit] do
      get 'edit', on: :collection
    end

    resources :buys, only: %i[index show] do
      member do
        put :state_change_accepted
        put :state_change_rejected
      end
    end
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  # -- Relations
  belongs_to :category
  has_many :product_tags
  has_many :tags, through: :product_tags
  has_many :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images, allow_destroy: true
  has_many :items

  # -- Validations
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :code, presence: true, uniqueness: true
  validates :category, presence: true
  validates :price,
            presence: true,
            numericality: {
              greater_than_or_equal_to: 0
            }
  validates :cost,
            presence: true,
            numericality: {
              greater_than_or_equal_to: 0
            }
  validate :only_one_image_checked

  before_destroy :check_buys



  # -- Scopes
  scope :with_name, ->(name) { where('name LIKE ?', "%#{name}%") }
  scope :with_category, ->(category_id) { where(category_id: category_id) }
  # scope :sort_asc_name,->{ order(name: :asc) }
  # scope :sort_desc_name, ->{ order(name: :desc) }
  scope :sort_name, ->(sort) { order(name: sort) }
  scope :actives, -> { where(active: true) }
  def only_one_image_checked
    return if product_images.select(&:principal).count == 1

    errors.add(:product_images, message: I18n.t(:only_one_image_error))
  end
  private 

  def check_buys
    return if self.items.count.zero?

    errors.add(:base, I18n.t(:destroy_products_error))
    throw(:abort)
  end
end

app/controllers/backend/buys_controller.rb
# frozen_string_literal: true

module Backend
  class BuysController < BackendController
    # authorize_resource class: false
    before_action :set_buy, except: [
      :index
    ]

    def index
      authorize! :index, :backend_buy
      @buys = Buy.all.decorate
    end

    def state_change_accepted
      if @buy.update_state(:accepted)
        flash.now[:notice] = t(:action_without_errors,
                               element: :Compra,
                               action: :actualizada)
      else
        flash.now[:alert] = t(:action_error,
                              element: :Compra,
                              action: :actualizada)
      end
      @buy.decorate
    end

    def state_change_rejected
      if @buy.update_state(:rejected)
        flash.now[:notice] = t(:action_without_errors,
                               element: :Compra,
                               action: :actualizada)
      else
        flash.now[:alert] = t(:action_error,
                              element: :Compra,
                              action: :actualizada)
      end
      @buy.decorate
    end

    def show
      @buy
      authorize! :show, :backend_buy
    end

    private

    def set_buy
      @buy = Buy.find(params[:id]).decorate
    end

    def buy_params
      params.require(:buy).permit(:id)
    end
  end
end

app/controllers/backend/categories_controller.rb
# frozen_string_literal: true

module Backend
  class CategoriesController < BackendController
    authorize_resource
    before_action :set_category, only: %i[
      show
      edit
      update
      destroy
    ]
    def index
      @categories = Category.all
    end

    def show; end

    def new
      @category = Category.new
      render :modal
    end

    def edit
      render :modal
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        flash.now[:notice] = t(:action_without_errors,
                               element: :Categoría,
                               action: :creada)
      else
        flash.now[:alert] =  t(:action_error,
                               element: :Categoría,
                               action: :creada)
        render :modal
      end
    end

    def update
      if @category.update(category_params)
        flash.now[:notice] = t(:action_without_errors,
                               element: :Categoría,
                               action: :creada)
      else
        flash.now[:alert] = t(:action_error,
                              element: :Categoría,
                              action: :creada)
        render :modal
      end
    end

    def destroy
      @category.destroy
      if @category.errors.present?
        flash[:alert] = @category.errors.full_messages.first
      else
        flash[:notice] = t(:action_without_errors,
                           element: :Categoría,
                           action: :eliminada)
      end
      redirect_to backend_categories_path
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/controllers/backend/clients_controller.rb
# frozen_string_literal: true

module Backend
  class ClientsController < BackendController
    # authorize_resource class: false
    before_action :set_client, except: [
      :index
    ]
    before_action :authorize_buy
    def index
      @clients = User.clients
    end

    def show; end

    def destroy
      @client.destroy
      if @client.errors.present?
        flash.now[:alert] = @client.errors[:error_user_destroy].first
      else
        flash.now[:notice] = t(:action_without_errors,
                              element: :cliente,
                              action: :eliminado)
      end
    end

    private

    def authorize_buy
      authorize! :authorize_client, :backend_client
    end

    def set_client
      @client = User.find(params[:id])
    end

    def client_params
      params.require(:user).permit(:id)
    end
  end
end

app/controllers/backend/configs_controller.rb
# frozen_string_literal: true

module Backend
  class ConfigsController < BackendController
    authorize_resource
    def edit
      render :modal
    end

    def new
      render :modal
    end

    def create
      update
    end

    def update
      if @config.update(config_params)
        flash.now[:notice] = t(:action_without_errors,
                               element: :Conifugración,
                               action: :actualizada)
        redirect_to backend_sliders_path
      else
        flash.now[:alert] = t(:action_error,
                            element: :Configuración,
                            action: :actualizada)
        render :modal
      end
    end

    private

    def config_params
      params.require(:config).permit(
        :logo,
        :per_page
      )
    end
  end
end

app/controllers/backend/main_controller.rb
# frozen_string_literal: true

module Backend
  class MainController < BackendController
    before_action :authorize_main
    def index; end

    private

    def authorize_main
      authorize! :authorize_main, :backend_main
    end
  end
end

app/controllers/backend/products_controller.rb
# frozen_string_literal: true

module Backend
  class ProductsController < BackendController
    before_action :set_product, only: %i[
      show
      edit
      update
      destroy
    ]
    before_action :authorize_product
    def index
      @presenter = ProductBackendPresenter.new(params)
    end

    def show; end

    def new
      @product = Product.new
    end

    def edit; end

    def create
      #binding.pry
      @product = Product.new(product_params)
      if @product.save
        flash[:notice] = t(:action_without_errors,
                               element: :Producto,
                               action: :creado)
        redirect_to backend_products_path
      else
       # binding.pry
        flash[:alert] = t(:action_error,
                              element: :Producto,
                              action: :creado)
        render :new
      end
    end

    def update
      if @product.update(product_params)
        flash[:notice] = t(:action_without_errors,
                               element: :Producto,
                               action: :actualizado)
        redirect_to backend_products_path
      else
        flash[:alert] = t(:action_error,
                              element: :Producto,
                              action: :actualizado)
        render :edit
      end
    end

    def destroy
      @product.destroy
      if @product.errors.present?
        flash[:alert] = @product.errors.full_messages.first
      else
        flash[:notice] = t(:action_without_errors,
          element: :Producto,
          action: :eliminado)
      end
      redirect_to backend_products_path
    end

    private

    def authorize_product
      authorize! :authorize_product, :backend_product
    end

    def set_product
      @product = Product.find(params[:id]).decorate
    end

    def product_params
      params.require(:product).permit(
        :name,
        :description,
        :active,
        :code,
        :price,
        :cost,
        :category_id,
        tag_ids: [],
        product_images_attributes: %i[
          id
          image
          principal
          _destroy
        ]
      )
    end
  end
end

app/controllers/backend/sliders_controller.rb
# frozen_string_literal: true

module Backend
  class SlidersController < BackendController
    before_action :set_slider, only: %i[
      edit
      update
      destroy
    ]
    authorize_resource
    def index
      @sliders = Slider.all
      @config = Config.last
    end

    def new
      @slider = Slider.new
      render :modal
    end

    def edit
      render :modal
    end

    def create
      @slider = Slider.new(slider_params)
      if @slider.save
        flash.now[:notice] = t(:action_without_errors,
                               element: :Slider,
                               action: :creado)
      else
        flash.now[:alert] = t(:action_error,
                              element: :Slider,
                              action: :creado)
        
        render :modal
      end
    end

    def update
      if @slider.update(slider_params)
        flash.now[:notice] = t(:action_without_errors,
                               element: :Slider,
                               action: :creado)
      else
        flash.now[:alert] = t(:action_error,
                              element: :Slider,
                              action: :creado)
        render :modal
      end
    end

    def destroy
      @slider.destroy
      flash.now[:notice] = t(:action_without_errors,
                             element: :Slider,
                             action: :eliminado)
    end

    private

    def set_slider
      @slider = Slider.find(params[:id])
    end

    def slider_params
      params.require(:slider).permit(:name, :image)
    end
  end
end

app/controllers/backend/tags_controller.rb
# frozen_string_literal: true

module Backend
  class TagsController < BackendController
    before_action :set_tag, only: %i[
      edit
      update
      destroy
    ]
    authorize_resource
    def index
      @tags = Tag.all
    end

    def new
      @tag = Tag.new
      render :modal
    end

    def edit
      render :modal
    end

    def create
      @tag = Tag.new(tag_params)
      if @tag.save
        flash.now[:notice] = t(:action_without_errors,
                               element: :Tag,
                               action: :creado)
      else
        flash.now[:alert] = t(:action_error,
                              element: :Tag,
                              action: :creado)
        render :modal
      end
    end

    def update
      if @tag.update(tag_params)
        flash.now[:notice] = t(:action_without_errors,
                               element: :Tag,
                               action: :actualizado)
      else
        flash.now[:alert] = t(:action_error,
                              element: :Tag,
                              action: :actualizado)
        render :modal
      end
    end

    def destroy
      @tag.destroy
      flash.now[:notice] = t(:action_without_errors,
                             element: :Tag,
                             action: :eliminado)
    end

    private

    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name)
    end
  end
end

app/controllers/backend/users_controller.rb
# frozen_string_literal: true

module Backend
  class UsersController < BackendController
    before_action :set_user, only: %i[edit
                                      update
                                      destroy]
    authorize_resource
    def index
      @users = User.admins
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      @user.set_default_password
      @user.set_profile_admin
      if @user.save
        flash.now[:notice] = t(:action_without_errors,
                           element: :Usuario,
                           action: :creado)
        redirect_to backend_users_path
      else
        flash.now[:alert] = t(:action_error,
                              element: :Usuario,
                              action: :creado)
        render :new
      end
    end

    def edit; end

    def update
      if @user.update(user_params)
        flash.now[:notice] = t(:action_without_errors,
                           element: :Usuario,
                           action: :actualizado)
        redirect_to backend_users_path
      else
        flash.now[:alert] = t(:action_error,
                              element: :Usuario,
                              action: :actualizado)
        render :edit
      end
    end

    def destroy
      if @user != current_user
        @user.destroy
        flash.now[:notice] = t(:action_without_errors,
                           element: :Usuario,
                           action: :eliminado)
      else
        flash.now[:alert] = t(:action_error,
                          element: :Usuario,
                          action: :eliminado)
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :email)
    end
  end
end

app/controllers/backend_controller.rb
# frozen_string_literal: true

class BackendController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/frontend/products_controller.rb
# frozen_string_literal: true

module Frontend
  class ProductsController < FrontendController
    #before_action :authorize_product
    def index
      @presenter = ProductPresenter.new(params)
      #@presenter = Product.all
    end

    def show
      @product = Product.find(params[:id]).decorate
    end
  end
end

app/views/backend/products/_filter.html.erb
<br>
<div class='d-flex justify-content-between form-group bg-secondary p-3 mb-2 text-white text-left'>
  <h2> Productos </h2>
  <%= form_with url: products_path, model:@presenter.filter,
                local:true,
                remote:true,
                method: :get, class: 'form-inline' do |f|
  %>
  <div class="form-group mx-sm-3 mb-2">
    <%= f.select(:sort, [['Activos', :true], ['Inactivos', :false]],{ include_blank: 'Todos' }, class: 'form-control mb-2 ') %>
  </div>
   <div class="form-group mx-sm-3 mb-2">
    <%= f.submit 'Buscar', class: 'btn btn-info mb-2' %>
  </div>
  <% end %>
</div>

app/views/backend/products/_form.html.erb
<%= render 'flash_message'%>
<%= form_with model: [:backend, @product], local: true do |f| %>
<div class="row">
  <div class="col-8">
    <div class="row">
      <div class="col">
        <div class="form-group">
          <%= f.label :name, 'Nombre' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <%= f.label :code, 'Código' %>
          <%= f.text_field :code, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="row form-group">
      <div class="col">
        <%= f.label :category_id, 'Categoría'%>
        <%= f.collection_select :category_id, Category.all, :id, :name, {}, class:'form-control' %>
      </div>
      <div class="col">
        <%= f.label :active, 'Activo' %>
        <%= f.check_box :active %>
      </div>
    </div>
    <div class="row form-group">
      <div class="col">
        <%= f.label :tags_ids, 'Tags'%>
        <%= f.collection_select :tag_ids, Tag.all, :id, :name, {}, class:'form-control', multiple: true %>
      </div>
    </div>
    <div class="row form-group">
      <div class="col">
        <%= f.label :price, 'Precio' %>
        <%= f.number_field :price, class: 'form-control' %>
      </div>
      <div class="col">
        <%= f.label :cost, 'Costo' %>
        <%= f.number_field :cost, class: 'form-control' %>
      </div>
    </div>
    <div class="row form-group">
      <div class="col">
        <%= f.label :description, 'Descripción' %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
    </div>
    <div class="row form-group">
      <div class="col">
        <br>
        <div class="form-group">
          <%= f.submit 'Guardar', class: 'btn btn-primary' %>
          <%= link_to 'Volver', backend_products_path %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-4">
    <div class="row form-group">
      <div class="col">
        <br>
        <div id='imagenes' class="card" >
          <div class='links'>
            <%= link_to_add_association 'add image', f, :product_images , class: 'btn btn-primary' %>
            <%= f.fields_for :product_images do |s| %>
              <%= render 'product_image_fields', f: s  %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/backend/products/_images_secondary.html.erb
<% image_tag(@product.image_principal, size:"75x75") %>

app/views/backend/products/_product.html.erb
<tr id='<%= dom_id(product) %>'>
  <td>
    <%= image_tag(product.image_principal, size:"25x25") %>
    <%= product.name %>
  </td>
  <td><%= product.active %></td>
  <td>
    <%= product.price %>
  </td>
  <td class='text-right'>
    <div >
      <%= link_to 'Ver', backend_product_path(product),  class: 'btn btn-sm btn-outline-info' %>
      <%= link_to 'Editar', edit_backend_product_path(product), class: 'btn btn-sm btn-outline-warning' %>
      <%= link_to 'Borrar', backend_product_path(product), method: :delete, data: { confirm: 'Esta seguro?' }, class: 'btn btn-sm btn-outline-danger' %>
    </div>
  </td>
</tr>

app/views/backend/products/_product_image_fields.html.erb
<div class='nested-fields card'>
  <div class='card-body'>
    <div class="form-group">

        <% if f.object.image.attached? %>
          <%= f.hidden_field :image, value: f.object.image.signed_id %>
          <%= image_tag f.object.image, class: 'img-fluid', style: 'width: 250px' %>
        <% end %>

        <%= f.file_field :image, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :principal, 'principal' %>
      <%= f.check_box :principal, class: 'js-card-checkbox' %>
      <br>
      <%= link_to_remove_association "remove image", f %>
    </div>
  </div>
</div>

app/views/backend/products/edit.html.erb
<h1>Editar Producto</h1>
<%= render 'form'%>

app/views/backend/products/index.html.erb
<!-- Button trigger modal -->
<br>
<%= render 'flash_message'%>

<table class="table table-bordered">
  <thead class="thead-light">
    <tr>
      <th>Productos</th>
      <th>Activo</th>
      <th>Precio</th>
      <th class="text-right"><%= link_to I18n.t(:new), new_backend_product_path, class: 'btn btn-primary' %></th>
    </tr>
  </thead>
  <tbody id='products_container'>
    <%= render @presenter.products %>
  </tbody>
</table>
<div class="row d-flex justify-content-center">
  <%= will_paginate @presenter.products%>
</div>

app/views/backend/products/new.html.erb
<h1 class="mt-2">Nuevo producto</h1>
<%= render 'form'%>

app/views/backend/products/show.html.erb
  <br>
  <h3>Producto #<%= @product.id %></h3>
  <div class="row">
    <div class="col-8">
      <table class="table table-striped">
        <tbody>
          <tr>
            <th scope="row">Nombre</th>
            <td><%= @product.name%></td>
          </tr>
          <tr>
            <th scope="row">Activo</th>
            <td><%= @product.active%></td>
          </tr>
          <tr>
            <th scope="row">Categoria</th>
            <td><%= @product.category_name%></td>
          </tr>
          <tr>
            <th scope="row">precio</th>
            <td><%= @product.pretty_price%></td>
          </tr>
          <tr>
            <th scope="row">Costo</th>
            <td><%= @product.pretty_cost%></td>
          </tr>
          <tr>
            <th scope="row">Tags</th>
            <td><%= @product.tags_name%></td>
          </tr>
          <tr>
            <th scope="row">Descripción</th>
            <td><%= @product.description%></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-4">
        <b><%= t('image_principal') %></b><br>
        <%= image_tag(@product.image_principal, size:"150x150") %>
      <hr>
      <h4><%= t('secondary_images') %></h4>
      <table class="table table-bordered scrolly">
        <tbody>
          <tr>
            <% @product.images_secondaries.each do |img| %>
              <%= image_tag(img, size:"100x100") %>
            <% end %>
          </tr>
        </tbody>
      </table>
</div>
  </div>



  <div class='card-footer'>
    <%= link_to 'Volver', backend_products_path, class: 'btn btn-outline-secondary' %>
  </div>