config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  scope module: :frontend do
    root to: 'main#home'
    resources :products, only: %i[index show]
    resources :buys, only: [:index, :show] do
      get 'create', to: 'buys#create', on: :collection, as: :create
    end
    get 'cart', to: 'cart#show'
    get 'add_product_to_cart/:id', to: 'cart#add_to_cart', as: 'add_product_to_cart'
    get 'remove_from_cart/:id', to: 'cart#remove_from_cart', as: 'remove_product_from_cart'
  end

  namespace :backend do
    root 'main#index'
    resources :users
    resources :categories
    resources :tags
    resources :sliders
    resources :products
    resources :clients, only: %i[index destroy]
    resources :configs, except: %i[show destroy index edit] do
      get 'edit', on: :collection
    end

    resources :buys, only: %i[index show] do
      member do
        put :state_change_accepted
        put :state_change_rejected
      end
    end
  end
end

app/controllers/frontend/buys_controller.rb
# frozen_string_literal: true
module Frontend
  class BuysController < FrontendController
    before_action :authorize_buy_client_logged

    def index
      @buys = current_user.buys
    end

    def show
      @buy = Buy.find(params[:id]).decorate
    end

    def create
      buy_manager = BuyManager.new(@cart, current_user)

      if buy_manager.create
        flash.now[:notice] = t(:buy_created_without_errors)
        redirect_to buys_path
      else
        flash.now[:alert] = t(:buy_created_without_errors)
        redirect_to cart_path
      end
    end

    private

    def authorize_buy_client_logged
      authorize! :authorize_buy_user_logged, :frontend_buy
    end
  end
end

app/controllers/frontend/cart_controller.rb
# frozen_string_literal: true
module Frontend
  class CartController < FrontendController
    #before_action :authorize_cart
    before_action :set_product_id, only: [:add_to_cart, :remove_from_cart]
    def show
      if @cart.size.zero?
        flash[:alert] = t(:the_cart_does_not_have_products)
        redirect_to root_path
      end
      @elements_cart = Cart.new(@cart)
    end

    def add_to_cart
      product_id = params[:id]
      if @cart[product_id].nil?
        @cart[product_id] = 1
      else
        @cart[product_id] += 1
      end
      render 'update_cart_notification'
    end

    def authorize_cart
      authorize! :authorize_cart, :frontend_cart
    end

    def remove_from_cart
      @cart.delete(params[:id])
      @elements_cart = Cart.new(@cart)
    end

    private

    def set_product_id
      @product_id = params[:id]
    end
  end
end

app/controllers/frontend/item_controller.rb
module Frontend
  class ItemController < FrontendController
    before_action :set_item

    def show; end

    def create; end

    private

    def set_item
      @item = Item.find(params[:id])
    end
  end
end

app/controllers/frontend/main_controller.rb
# frozen_string_literal: true

module Frontend
  class MainController < FrontendController
    #before_action :authorize_home
    def home
      @sliders = Slider.all
      @products = Product.actives.order("RAND()").limit(4).decorate
    end
  end
end

app/controllers/frontend/products_controller.rb
# frozen_string_literal: true

module Frontend
  class ProductsController < FrontendController
    #before_action :authorize_product
    def index
      @presenter = ProductPresenter.new(params)
      #@presenter = Product.all
    end

    def show
      @product = Product.find(params[:id]).decorate
    end
  end
end

app/controllers/frontend_controller.rb
# frozen_string_literal: true

class FrontendController < ApplicationController
end

app/views/frontend/cart/_add_to_cart.html.erb
<div class="container">
  <button class="button float-left">-</button>
  <input type="number" class="input" value="1" min="1">
  <button class="button float-right">+</button>
  <a href="" data-id="1" data-quantity="1" class="add-to-cart ajax product-2">
    <%= image_tag("add.png", size: "20x20") %>
  </a>
</div>

app/views/frontend/cart/_cart_final_count.html.erb
<span id="cart_count">
<%= @elements_cart.total_products %>
</span>

app/views/frontend/cart/_cart_price_total.html.erb
<span id="cart_price_total">
<%= @elements_cart.price_total  %>
</span>

app/views/frontend/cart/_items_in_cart.html.erb
<% @cart.each do |id_product, count| %>
<tr id="item-<%= id_product %>">
  <td><%= image_tag(Product.find(id_product).decorate.image_principal, size: "25x25") %><%= Product.find(id_product).name %></td>
  <td>$ <%= Product.find(id_product).price %></td>
  <td><%= count %></td>
  <td>$ <%= count * Product.find(id_product).price %></td>
  <td><%= link_to image_tag('close.png', size: "20x20"), remove_product_from_cart_path(id_product), remote: true, class: "btn btn-outline-danger" %></td>
</tr>
<% end %>

app/views/frontend/cart/remove_from_cart.js.erb
<% if @cart == {} %>
  window.location.href = "/cart";
<% end %>
$('#cart_count').replaceWith('<%= j render 'cart_final_count', cart: @cart %>');
$('#cart_price_total').replaceWith('<%= j render 'cart_price_total', cart: @cart %>');
$('#item-<%= @product_id %>').remove();

app/views/frontend/cart/show.html.erb
<%= render 'flash_message' %>

<div class='d-flex justify-content-between  p-3 mb-2 text-left'>
<div class= "container-fluid"> 
<h2> Mi Carrito </h2>
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col"><%= I18n.t(:product) %></th>
      <th scope="col"><%= I18n.t(:price) %></th>
      <th scope="col"><%= I18n.t(:count) %></th>
      <th scope="col"><%= I18n.t(:subtotal) %></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
   <%= render "items_in_cart" %>
   <tr class="bg-secondary text-white">
   <td colspan="2"><%= I18n.t(:total) %></td>
   <td class= "text-left"> <%= render "cart_final_count" %> </td>
   <td colspan="2"> $ <%=render "cart_price_total" %> </td>
   </tr>
  </tbody>
</table>


  <% if (can? :authorize_close_car, :frontend_cart) %>
    <%= link_to I18n.t(:make_an_order), create_buys_path, class: 'btn btn-success' %>
  <% else %>
    <p class="text-secondary">
    <%= I18n.t(:you_must_login) %>
    </p>
    <%= link_to ' Iniciar sesión', new_user_session_path,{method: :post, class: 'btn btn-primary'}%>
  <% end %>
</div>
</div>

app/views/frontend/cart/update_cart.js.erb
$('#item-<%= @product_id %>').remove();

app/views/frontend/cart/update_cart_notification.js.erb
$('#cart-notifier-id').text("<%= @cart.size %>");